
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: web-client-hpa
  labels:
    app.kubernetes.io/instance: web-client
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: web-client
    helm.sh/chart: web-client-0.1.0
spec:
  maxReplicas: 24
  minReplicas: 6
  targetCPUUtilizationPercentage: 50
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: web-client
