apiVersion: v1
kind: Pod
metadata:
  name: test-workshop-pod2
  labels:
    app.kubernetes.io/name: rf-primary-receiver
    app.kubernetes.io/instance: rf-primary-receiver
    joom.com/env: production
    joom.com/service: "joom-rf-primary-receiver-openresty"
    joom.com/version: master-3190777.1573226822
  annotations:
    checksum/configmap: 84eb1dcf63b5581257554b888b4809970ac9ee923a5a479571cff4a7d1f71cf7
spec:
  initContainers:
    - name: joom-rf-primary-receiver-etcd-register
      image: docker.joom.it/rf-receiver-etcd-register:master-3190777.1573226822
      imagePullPolicy: IfNotPresent
      env:
        - name: HOST_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
      command: ["bash", "-c"]
      args:
        - >
          EXTERNAL_IP1=$(curl -s https://ipinfo.io/json | jq -cr ".ip");
          EXTERNAL_IP2=$(curl -s https://ifconfig.co/json | jq -cr ".ip");
          [[ -z "$EXTERNAL_IP1" ]] && EXTERNAL_IP="$EXTERNAL_IP2" || EXTERNAL_IP="$EXTERNAL_IP1";
          [[ -z "$EXTERNAL_IP" ]] && echo "couldn't get EXTERNAL_IP from 2 sites" || echo "use EXTERNAL_IP:$EXTERNAL_IP";
          [[ -z "$EXTERNAL_IP" ]] && exit 1;
          echo "HOST_NODE_NAME: $HOST_NODE_NAME";

          echo etcdctl --endpoints=etcd.joom.x:2379 get proxy-registry/v1/hosts/${HOST_NODE_NAME};
          etcdctl --endpoints=etcd.joom.x:2379 get proxy-registry/v1/hosts/${HOST_NODE_NAME};
          echo 'echo -e "external_ip: ${EXTERNAL_IP}\nupdated: $(date -u +"%Y-%m-%dT%H:%M:%SZ")" | etcdctl --endpoints=etcd.joom.x:2379 put proxy-registry/v1/hosts/${HOST_NODE_NAME}';
          echo -e "external_ip: ${EXTERNAL_IP}\nupdated: $(date -u +"%Y-%m-%dT%H:%M:%SZ")" | etcdctl --endpoints=etcd.joom.x:2379 put proxy-registry/v1/hosts/${HOST_NODE_NAME};
          echo "DONE";
          echo etcdctl --endpoints=etcd.joom.x:2379 get proxy-registry/v1/hosts/${HOST_NODE_NAME};
          etcdctl --endpoints=etcd.joom.x:2379 get proxy-registry/v1/hosts/${HOST_NODE_NAME};

          echo etcdctl --endpoints=etcd.joom.x:2379 get proxy-registry/v1/traefik-hosts/${HOST_NODE_NAME};
          etcdctl --endpoints=etcd.joom.x:2379 get proxy-registry/v1/traefik-hosts/${HOST_NODE_NAME};
          echo 'echo -e "external_ip: ${EXTERNAL_IP}\nupdated: $(date -u +"%Y-%m-%dT%H:%M:%SZ")" | etcdctl --endpoints=etcd.joom.x:2379 put proxy-registry/v1/traefik-hosts/${HOST_NODE_NAME}';
          echo -e "external_ip: ${EXTERNAL_IP}\nupdated: $(date -u +"%Y-%m-%dT%H:%M:%SZ")" | etcdctl --endpoints=etcd.joom.x:2379 put proxy-registry/v1/traefik-hosts/${HOST_NODE_NAME};
          echo "DONE";
          echo etcdctl --endpoints=etcd.joom.x:2379 get proxy-registry/v1/traefik-hosts/${HOST_NODE_NAME};
          etcdctl --endpoints=etcd.joom.x:2379 get proxy-registry/v1/traefik-hosts/${HOST_NODE_NAME};
  containers:
    - name: joom-rf-primary-receiver-openresty
      image: "docker.joom.it/rf-receiver-openresty:master-3190777.1573226822"
      imagePullPolicy: IfNotPresent
      ports:
        - name: http
          containerPort: 80
          protocol: TCP
        - name: metrics
          containerPort: 8080
          protocol: TCP
      livenessProbe:
        httpGet:
          path: /ping
          port: metrics
      readinessProbe:
        httpGet:
          path: /ping
          port: metrics
      volumeMounts:
        - name: nginx-conf
          mountPath: /etc/rf-receiver/nginx/
    - name: dnsmasq
      image: "janeczku/go-dnsmasq:release-1.0.7"
      args:
        - --listen
        - "127.0.0.1:53"
        - --default-resolver
        - --append-search-domains
        - --hostsfile=/etc/hosts
        - --hostsfile-poll=4
        - --verbose
  volumes:
    - name: nginx-conf
      configMap:
        name: configmap-openresty
  tolerations:
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
    - effect: NoSchedule
      key: node.kubernetes.io/disk-pressure
      operator: Exists
    - effect: NoSchedule
      key: node.kubernetes.io/memory-pressure
      operator: Exists
    - effect: NoSchedule
      key: node.kubernetes.io/pid-pressure
      operator: Exists
    - effect: NoSchedule
      key: node.kubernetes.io/unschedulable
      operator: Exists