apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: test-workshop-rs
  labels:
    name: test-workshop-namespace
    app: test-workshop
spec:
  replicas: 3
  selector:
    matchLabels:
      app: test-workshop
  template:
    metadata:
      labels:
        app: test-workshop
    spec:
      containers:
        - name: php-redis
          image: gcr.io/google_samples/gb-frontend:v3