apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: test-workshop-ingress
  namespace: test-nginx-ingress-v2
  labels:
    name: test-workshop-ingress
    app: test-workshop
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/canary: "true"
    nginx.ingress.kubernetes.io/canary-by-cookie: "joomcanary"
    nginx.ingress.kubernetes.io/canary-weight: "25"
    nginx.ingress.kubernetes.io/affinity: cookie
    nginx.ingress.kubernetes.io/affinity-mode: balanced
    nginx.ingress.kubernetes.io/session-cookie-name: joomsessionv2
    nginx.ingress.kubernetes.io/session-cookie-max-age: "30"
    nginx.ingress.kubernetes.io/session-cookie-change-on-failure: "true"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_headers "Set-Cookie: test2=2";
spec:
  rules:
    - host: testingress.sandbox.k8s.joomdev.net
      http:
        paths:
          - path: /
            backend:
              serviceName: test-workshop-v2-svc
              servicePort: 80
